name: Next Integration

on:
  pull_request

env:
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  PAGES_PROJECT_NAME: we-up-next
  DEPLOY_TAG: we-up-next-stage-${{ github.event.number }}
  DEPLOY_ROUTE: https://we-up-next-stage-${{ github.event.number }}.we-up-next.pages.dev
  AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
  AUTH0_ISSUER_BASE_URL: https://rakerman.us.auth0.com
  AUTH0_CLIENT_ID: Vo3Xv3M9AvgOdrYAdFnLvyjsTXOda3zm
  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
  BACKEND_BASE_URL: https://we-up-hono-stage-${{ github.event.number }}.we-up-next.pages.dev

jobs:
  format_checks:
    name: Format Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: next/package-lock.json

      - name: Install Dependencies
        run: npm ci
        working-directory: next 

      - name: Check Next Lint
        run: npm run check-lint
        working-directory: next 

  cf_deploy_next_stage:
    name: Deploy Next to Stage
    runs-on: ubuntu-latest
    needs: format_checks

    environment:
      name: next-stage-${{ github.event.number }}
      url: ${{ env.DEPLOY_ROUTE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: next/package-lock.json

      - name: Install Dependencies
        run: npm ci
        working-directory: next

      - name: Build Cloudflare Next on Pages
        run: npm run pages:build
        working-directory: next

      - name: Deploy Next
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          command: |
            pages deploy .vercel/output/static \
              --project-name ${{ env.PAGES_PROJECT_NAME }} \
              --branch ${{ env.DEPLOY_TAG }} \
              --binding AUTH0_SECRET=${{ env.AUTH0_SECRET }} \
              --binding AUTH0_BASE_URL=${{ env.DEPLOY_ROUTE }} \
              --binding AUTH0_ISSUER_BASE_URL=${{ env.AUTH0_ISSUER_BASE_URL }} \
              --binding AUTH0_CLIENT_ID=${{ env.AUTH0_CLIENT_ID }} \
              --binding AUTH0_CLIENT_SECRET=${{ env.AUTH0_CLIENT_SECRET }} \
              --binding BACKEND_BASE_URL=${{ env.BACKEND_BASE_URL }}
          workingDirectory: next
 